
development:
  adapter: postgresql
  encoding: unicode
  database: shopping_development
  username: postgres
  password: kishore
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: shopping_development
  username: postgres
  password: kishore
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: shopping_development
  username: postgres
  password: kishore
  host: localhost
  port: 5432